version: '3.3'
services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
        - ./frontend.html:/usr/share/nginx/html/index.html
    expose:
      - 80
    # ports:
    #   - 81:80

  api1:
    container_name: api1
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 1000 
    expose:
      - 1000
    # ports:
    #   - 1000:1000

  api2:
    container_name: api2
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn example:app --reload --host 0.0.0.0 --port 2000
    expose:
      - 2000
    # ports:
    #   - 2000:2000


  nginx-proxy:
    image: nginx/unit:1.26.1-minimal
    container_name: nginx-proxy
    volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api1
      - api2
    ports:
      - 1234:80
