version: '3.3'
services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
        - ./frontend.html:/usr/share/nginx/html/index.html
    networks:
        my-network-name:
            aliases:
                - frontend

  api1:
    container_name: api1
    hostname: api1
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn app:app --reload
    networks:
        my-network:
            aliases:
                - api1

  api2:
    container_name: api2
    hostname: api2
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn app:app --reload
    networks:
        my-network:
            aliases:
                - api2

  nginx-proxy:
    image: nginx/unit:1.26.1-minimal
    container_name: nginx-proxy
    hostname: nginx_proxy
    volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api_1
      - api_2
    environment:
      - TZ=America/NewYork
    ports:
      - 1234:80
    volumes:
      - operator_nodered:/data
    networks:
      - api-network 

networks:
  my-network: